// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_ME_cpp
double compute_ME_cpp(const NumericVector& beta_hat, const NumericVector& beta0, const NumericMatrix& Sigma);
RcppExport SEXP _SA25204153_compute_ME_cpp(SEXP beta_hatSEXP, SEXP beta0SEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type beta_hat(beta_hatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_ME_cpp(beta_hat, beta0, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// compute_C_IC_cpp
NumericVector compute_C_IC_cpp(const NumericVector& beta_hat, const NumericVector& beta0, double tol);
RcppExport SEXP _SA25204153_compute_C_IC_cpp(SEXP beta_hatSEXP, SEXP beta0SEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type beta_hat(beta_hatSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_C_IC_cpp(beta_hat, beta0, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA25204153_compute_ME_cpp", (DL_FUNC) &_SA25204153_compute_ME_cpp, 3},
    {"_SA25204153_compute_C_IC_cpp", (DL_FUNC) &_SA25204153_compute_C_IC_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA25204153(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
